export enum HEADER {
  // 设置和获取文章类型
  GET_ARTICLE_TYPE = 'GET_ARTICLE_TYPE',
  SET_ARTICLE_TYPE = 'SET_ARTICLE_TYPE',

  // 控制顶部header的显示和隐藏
  SET_HEADER_SHOW = 'SET_HEADER_SHOW',
  SET_HEADER_HIDE = 'SET_HEADER_HIDE',
}
